package com.pandy.jbpm

import com.pandy.rulemodel.HelloProcessModel;

rule "NYuser_Rule"
	
	no-loop true
	ruleflow-group "EvalLoopcondition"
	when
		$m:HelloProcessModel(userlocation in ("NewYorkUser"), count < 4)
	then
	      System.out.println("\nEvalLoopcondition - NewYorkUser : count=" + $m.getCount());
	      System.out.println("为循环设定条件");
	      $m.setLoopcondition(6);update($m);
end


rule "ChileUser_Rule"
	
	no-loop true
	ruleflow-group "EvalLoopcondition"
	when
		$m:HelloProcessModel(userlocation in ("ChileUser"), count < 3)
	then
	    System.out.println("\nEvalLoopcondition - ChileUser : count=" + $m.getCount());
	    System.out.println("为循环设定条件");
		$m.setLoopcondition(5);update($m);
end


rule "BelgiumUser_Rule"
	
	no-loop true
	ruleflow-group "EvalLoopcondition"
	when
		$m:HelloProcessModel(userlocation in ("BelgiumUser"), count < 6)
	then
	    System.out.println("\nEvalLoopcondition - BelgiumUser : count=" + $m.getCount());
	    System.out.println("为循环设定条件");
		$m.setLoopcondition(8);update($m);
end
